//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comandas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_comandas()
        {
            this.tbl_detallescomanda = new HashSet<tbl_detallescomanda>();
        }
    
        public string idcomanda { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int num_comanda { get; set; }
        public string idmesa { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<bool> para_llevar { get; set; }
        public string idpersona { get; set; }
        public string crea_usuario { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detallescomanda> tbl_detallescomanda { get; set; }
    }
}
