//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detallescomanda
    {
        public string iddetalle { get; set; }
        public string idcomanda { get; set; }
        public string iditem { get; set; }
        public string idobservaciones { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
