//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items
    {
        public string iditem { get; set; }
        public string idlstipoitem { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string crea_usuario { get; set; }
    
        public virtual tbl_listadoseldetalle tbl_listadoseldetalle { get; set; }
    }
}
