//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personas
    {
        public string idpersona { get; set; }
        public string idlstipopersona { get; set; }
        public string nprimario { get; set; }
        public string nsecundario { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public string razon_social { get; set; }
    }
}
