//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_items()
        {
            this.tbl_detallemenu = new HashSet<tbl_detallemenu>();
            this.tbl_detallesguarnicion = new HashSet<tbl_detallesguarnicion>();
            this.tbl_detallescomanda = new HashSet<tbl_detallescomanda>();
        }
    
        public string iditem { get; set; }
        public string idlstipoitem { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string crea_usuario { get; set; }
        public Nullable<bool> inventariable { get; set; }
    
        public virtual tbl_listadoseldetalle tbl_listadoseldetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detallemenu> tbl_detallemenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detallesguarnicion> tbl_detallesguarnicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detallescomanda> tbl_detallescomanda { get; set; }
    }
}
