//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_corte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_corte()
        {
            this.tbl_corte_mov = new HashSet<tbl_corte_mov>();
        }
    
        public string idcorte { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> total_ingreso { get; set; }
        public Nullable<decimal> total_egreso { get; set; }
        public Nullable<decimal> saldo_corte { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string crea_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_corte_mov> tbl_corte_mov { get; set; }
    }
}
