//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lista_ordenes
    {
        public string idorden { get; set; }
        public string iditem { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string nombreguarnicion { get; set; }
        public string cveitem { get; set; }
    }
}
