//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lista_productos
    {
        public string iditem { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string unidad { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<bool> inventariable { get; set; }
    }
}
