//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guajiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_proveedores_directorio
    {
        public string idpersona { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
